name: SpigotCore
main: com.gotofinal.darkrise.spigot.core.DarkRiseCore
author: GotoFinal
version: ${rise.version}-test
load: startup
loadbefore: [Economy]
softdepend: [WorldEdit, WorldGuard, ProtocolLib, TerrainControl]
depend: [LibraryPack]
